import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BarChart3, CalendarClock, Check, CreditCard, MessageCircle, ShieldCheck, Sparkles, Target, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/finanzzi/Logo";
import { ThemeToggle } from "@/components/finanzzi/ThemeToggle";
import { Reveal } from "@/components/finanzzi/Reveal";
import { PhoneMockup } from "@/components/finanzzi/landing/PhoneMockup";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "FINANZZI — Inteligência para o seu dinheiro" },
    { name: "description", content: "Organize seus gastos, contas, cartões e metas e descubra quanto você realmente pode gastar." },
    { property: "og:title", content: "FINANZZI — Inteligência para o seu dinheiro" },
    { property: "og:description", content: "Controle seu dinheiro sem planilhas. Veja o que entra, o que sai e quanto você pode gastar." },
  ] }), component: Landing,
});

const MONTHLY = "https://pay.hub.la/CdKkw7B2b9JU8lBtzrOr";
const ANNUAL = "https://pay.hub.la/S3jNeWuq3E7no1fMZZ8r";
const features = [
  [Wallet, "Movimentações", "Registre entradas e saídas em poucos segundos, até escrevendo do seu jeito."],
  [CalendarClock, "Contas em dia", "Tenha vencimentos e compromissos à vista antes que virem surpresa."],
  [CreditCard, "Cartões sob controle", "Acompanhe faturas, limites e compras parceladas sem se perder."],
  [Target, "Metas", "Transforme seus planos em objetivos e acompanhe seu progresso."],
  [BarChart3, "Seus hábitos", "Entenda para onde seu dinheiro está indo com uma visão simples."],
  [MessageCircle, "Fin", "Pergunte sobre seu dinheiro e receba respostas baseadas nos seus dados."],
] as const;

function CheckoutButton({ href, children }: { href: string; children: React.ReactNode }) {
  return <Button asChild size="lg" className="h-12 rounded-full px-7 text-base"><a href={href}>{children}<ArrowRight className="ml-1 size-4" /></a></Button>;
}

function Landing() {
  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <header className="sticky top-0 z-40 px-3 pt-3 sm:px-6 sm:pt-5"><div className="mx-auto flex h-14 max-w-6xl items-center justify-between rounded-full border border-border bg-card/85 px-3 pl-5 shadow-[var(--shadow-soft)] backdrop-blur-xl sm:h-16"><Logo /><nav className="hidden items-center gap-5 text-sm text-muted-foreground lg:flex"><a href="#como-funciona" className="hover:text-foreground">Como funciona</a><a href="#recursos" className="hover:text-foreground">Recursos</a><a href="#precos" className="hover:text-foreground">Preços</a><a href="#faq" className="hover:text-foreground">FAQ</a></nav><div className="flex items-center gap-1.5 sm:gap-2"><ThemeToggle /><Button asChild variant="ghost" className="hidden rounded-full sm:inline-flex"><Link to="/auth" search={{ mode: "login" }}>Entrar</Link></Button><CheckoutButton href={MONTHLY}>Começar</CheckoutButton></div></div></header>
    <main>
      <section className="relative overflow-hidden px-4 pt-14 pb-20 sm:px-6 sm:pt-20 sm:pb-28"><div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-[700px] bg-[radial-gradient(ellipse_at_50%_0%,color-mix(in_oklab,var(--color-primary)_16%,transparent),transparent_62%)]" /><div className="relative mx-auto max-w-5xl text-center"><span className="animate-fin-fade-up inline-flex items-center gap-2 rounded-full border border-border bg-card px-3.5 py-1.5 text-xs font-semibold text-muted-foreground"><Sparkles className="size-3.5 text-primary" /> Inteligência para o seu dinheiro</span><h1 className="animate-fin-fade-up mt-6 font-display text-[2.65rem] leading-[0.98] font-extrabold tracking-[-0.045em] text-balance sm:text-7xl">Seu dinheiro.<br /><span className="text-primary">Finalmente sob controle.</span></h1><p className="animate-fin-fade-up mx-auto mt-6 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Organize contas, cartões, gastos e metas — e descubra quanto você realmente pode gastar antes de tomar uma decisão.</p><div className="animate-fin-fade-up mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><CheckoutButton href={MONTHLY}>Começar agora</CheckoutButton><Button asChild size="lg" variant="outline" className="h-12 w-full rounded-full px-7 text-base sm:w-auto"><a href="#como-funciona">Ver como funciona</a></Button></div><div className="mt-7 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Check className="size-4 text-primary" /> Fácil de usar</span><span className="inline-flex items-center gap-1.5"><ShieldCheck className="size-4 text-primary" /> Seus dados protegidos</span><span className="inline-flex items-center gap-1.5"><Sparkles className="size-4 text-primary" /> Fin incluído</span></div><div className="mx-auto mt-8 max-w-md rounded-2xl border border-primary/20 bg-card/90 px-5 py-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Acesso completo</p><div className="mt-1 flex items-baseline justify-center gap-2"><strong className="font-display text-3xl font-extrabold">R$ 19,90</strong><span className="text-sm text-muted-foreground">/mês</span></div><p className="mt-1 text-xs text-muted-foreground">ou R$ 179,10/ano · <span className="font-semibold text-primary">3 meses grátis</span></p></div></div><div className="relative mt-14 sm:mt-18"><PhoneMockup /></div></section>
      <section id="como-funciona" className="border-y border-border bg-card/60"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24"><Reveal className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold tracking-[0.18em] text-primary uppercase">Clareza financeira</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-0.035em] sm:text-5xl">Você sabe quanto tem. Mas sabe quanto pode gastar?</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-muted-foreground sm:text-base">O FINANZZI transforma o que entra, o que sai e o que ainda está comprometido em uma visão que faz sentido para a sua vida.</p></Reveal><div className="mt-12 grid gap-4 sm:grid-cols-3"><Reveal><div className="surface-card p-6"><span className="font-display text-4xl font-extrabold text-primary/30">01</span><h3 className="mt-3 font-display text-lg font-bold">Organize</h3><p className="mt-1.5 text-sm leading-6 text-muted-foreground">Contas, cartões, gastos e metas em um único lugar.</p></div></Reveal><Reveal delay={80}><div className="surface-card p-6"><span className="font-display text-4xl font-extrabold text-primary/30">02</span><h3 className="mt-3 font-display text-lg font-bold">Entenda</h3><p className="mt-1.5 text-sm leading-6 text-muted-foreground">Veja para onde seu dinheiro está indo e reconheça seus hábitos.</p></div></Reveal><Reveal delay={160}><div className="surface-card p-6"><span className="font-display text-4xl font-extrabold text-primary/30">03</span><h3 className="mt-3 font-display text-lg font-bold">Decida</h3><p className="mt-1.5 text-sm leading-6 text-muted-foreground">Descubra quanto pode gastar antes de dizer sim para uma compra.</p></div></Reveal></div></div></section>
      <section id="recursos" className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24"><Reveal className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold tracking-[0.18em] text-primary uppercase">O produto</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-0.035em] sm:text-5xl">Menos planilhas. Mais clareza.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground sm:text-base">Tudo que você precisa para parar de adivinhar o que acontece com seu dinheiro.</p></Reveal><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, text], i) => <Reveal key={title} delay={i * 60}><div className="surface-card h-full p-6 transition-transform hover:-translate-y-1"><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h3 className="mt-5 font-display text-lg font-bold tracking-tight">{title}</h3><p className="mt-1.5 text-sm leading-6 text-muted-foreground">{text}</p></div></Reveal>)}</div></section>
      <section className="px-4 pb-16 sm:px-6 sm:pb-24"><Reveal className="mx-auto max-w-5xl"><div className="gradient-stage relative overflow-hidden rounded-[2rem] px-6 py-14 text-center text-primary-foreground sm:px-12 sm:py-20"><span className="relative inline-flex items-center gap-2 rounded-full bg-white/12 px-3.5 py-1.5 text-xs font-semibold"><MessageCircle className="size-3.5" /> A pergunta que muda tudo</span><h2 className="relative mt-6 font-display text-3xl font-extrabold tracking-[-0.035em] sm:text-5xl">“Quanto eu posso gastar?”</h2><div className="relative mx-auto mt-8 max-w-sm rounded-3xl bg-white/10 p-6 backdrop-blur"><p className="text-sm opacity-80">Você pode gastar</p><p className="mt-1 font-display text-5xl font-extrabold">R$ 847,32</p><p className="mt-3 text-xs leading-5 opacity-75">Depois de considerar suas contas, compromissos e objetivos.</p></div><p className="relative mx-auto mt-6 max-w-xl text-sm leading-7 opacity-85 sm:text-base">O FINANZZI transforma números espalhados em uma resposta simples para a sua próxima decisão.</p><div className="relative mt-8"><CheckoutButton href={MONTHLY}>Quero ter essa clareza</CheckoutButton></div></div></Reveal></section>
      <section className="border-y border-border bg-card/60"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24"><div className="grid items-center gap-10 lg:grid-cols-2"><Reveal><p className="text-xs font-bold tracking-[0.18em] text-primary uppercase">Registro rápido</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-0.035em] sm:text-5xl">Registrar um gasto não deveria dar trabalho.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-muted-foreground sm:text-base">Escreva como você fala. O FINANZZI entende e organiza o lançamento para você.</p><div className="mt-8 rounded-3xl border border-border bg-background p-5 shadow-sm"><p className="text-sm font-medium">“gastei 45 reais no mercado”</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><div className="rounded-2xl bg-card p-3"><span className="text-xs text-muted-foreground">Valor</span><p className="font-bold">R$ 45,00</p></div><div className="rounded-2xl bg-card p-3"><span className="text-xs text-muted-foreground">Categoria</span><p className="font-bold">Alimentação</p></div></div></div></Reveal><Reveal delay={120}><PhoneMockup /></Reveal></div></div></section>
      <section id="precos" className="mx-auto max-w-5xl px-4 py-16 sm:px-6 sm:py-24"><Reveal className="text-center"><p className="text-xs font-bold tracking-[0.18em] text-primary uppercase">Planos</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-0.035em] sm:text-5xl">Comece a organizar seu dinheiro hoje.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-muted-foreground">Escolha o ritmo que faz sentido para você. O acesso é completo nos dois planos.</p></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2"><Reveal><div className="surface-card h-full p-7 sm:p-8"><p className="text-sm font-bold">FINANZZI Mensal</p><p className="mt-5 font-display text-5xl font-extrabold tracking-tight">R$ 19,90<span className="text-base font-medium text-muted-foreground">/mês</span></p><p className="mt-2 text-sm text-muted-foreground">Acesso completo, mês a mês.</p><div className="my-7 h-px bg-border" /><div className="space-y-3 text-sm">{["Movimentações e categorias", "Contas e cartões", "Metas e análises", "Quanto posso gastar?", "Fin e registro rápido"].map(x => <p key={x} className="flex items-center gap-2"><Check className="size-4 text-primary" />{x}</p>)}</div><div className="mt-8"><CheckoutButton href={MONTHLY}>Começar por R$ 19,90</CheckoutButton></div></div></Reveal><Reveal delay={100}><div className="relative h-full rounded-3xl border-2 border-primary bg-card p-7 shadow-[var(--shadow-soft)] sm:p-8"><span className="absolute right-5 top-5 rounded-full bg-primary px-3 py-1 text-[10px] font-bold tracking-wider text-primary-foreground uppercase">Mais econômico</span><p className="text-sm font-bold">FINANZZI Anual</p><p className="mt-5 font-display text-5xl font-extrabold tracking-tight">R$ 179,10<span className="text-base font-medium text-muted-foreground">/ano</span></p><p className="mt-2 text-sm text-muted-foreground"><s>R$ 238,80</s> · equivale a R$ 14,93/mês</p><p className="mt-3 inline-flex rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">Economize R$ 59,70 · 3 meses grátis</p><div className="my-7 h-px bg-border" /><div className="space-y-3 text-sm">{["Tudo do plano mensal", "Acesso completo por 12 meses", "Economia de R$ 59,70", "3 meses grátis"].map(x => <p key={x} className="flex items-center gap-2"><Check className="size-4 text-primary" />{x}</p>)}</div><div className="mt-8"><CheckoutButton href={ANNUAL}>Quero o plano anual</CheckoutButton></div></div></Reveal></div></section>
      <section id="faq" className="border-t border-border bg-card/60"><div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-24"><Reveal className="text-center"><p className="text-xs font-bold tracking-[0.18em] text-primary uppercase">Dúvidas</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-0.035em] sm:text-5xl">Antes de começar</h2></Reveal><div className="mt-10 divide-y divide-border rounded-3xl border border-border bg-card">{[["Quanto custa o FINANZZI?", "O plano mensal custa R$ 19,90 por mês. O anual custa R$ 179,10 e representa uma economia de R$ 59,70, equivalente a 3 meses grátis."],["Posso usar pelo celular?", "Sim. O FINANZZI foi pensado para funcionar muito bem no celular e também pode ser instalado como aplicativo pelo navegador."],["Como recebo acesso depois da compra?", "Depois da confirmação do pagamento, você recebe as instruções de acesso para entrar ou criar sua conta FINANZZI."],["Posso cancelar o plano mensal?", "Sim. O plano mensal pode ser cancelado para evitar a próxima cobrança, conforme as condições da assinatura."],["Meus dados ficam separados?", "Sim. Cada conta possui seus próprios dados e o sistema utiliza controle de acesso para impedir que usuários vejam informações de outras contas."]].map(([q,a]) => <details key={q} className="group p-5"><summary className="cursor-pointer list-none font-semibold">{q}<span className="float-right text-primary">+</span></summary><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{a}</p></details>)}</div></div></section>
      <section className="mx-auto max-w-5xl px-4 py-16 sm:px-6 sm:py-24"><Reveal><div className="gradient-stage rounded-[2rem] px-6 py-14 text-center text-primary-foreground sm:px-12 sm:py-20"><h2 className="font-display text-3xl font-extrabold tracking-[-0.035em] sm:text-5xl">Seu dinheiro não precisa ser complicado.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 opacity-85 sm:text-base">Comece hoje a ter clareza sobre o que entra, o que sai e o que você realmente pode gastar.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><CheckoutButton href={MONTHLY}>Começar por R$ 19,90</CheckoutButton><a href={ANNUAL} className="text-sm font-semibold underline underline-offset-4">Economizar R$ 59,70 no plano anual</a></div></div></Reveal></section>
    </main>
    <footer className="border-t border-border py-10"><div className="mx-auto flex max-w-6xl flex-col items-center gap-2 px-4 text-center"><Logo /><p className="text-xs text-muted-foreground">Inteligência para o seu dinheiro.</p><p className="mt-2 text-xs text-muted-foreground">© {new Date().getFullYear()} FINANZZI</p></div></footer>
  </div>;
}
