import { ArrowDownRight, ArrowUpRight, Car, Plus, ShoppingBag, Sparkles } from "lucide-react";

/**
 * Palco principal da landing: celular com uma mini-UI real do FINANZZI
 * cercado por chips de movimentações flutuantes (referência Pierre).
 */
export function PhoneMockup() {
  return (
    <div className="relative mx-auto w-full max-w-lg">
      <div aria-hidden className="absolute top-1/2 left-1/2 -z-10 size-[420px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/10 blur-[100px]" />
      <div className="animate-float-a pointer-events-none absolute hidden sm:block top-[16%] -left-1 z-30 sm:-left-12"><div className="flex min-w-[170px] items-center gap-3 rounded-2xl border border-border bg-card p-3.5 shadow-[var(--shadow-lift)]"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-muted text-primary"><ShoppingBag className="size-5" /></span><span><span className="block text-[10px] font-bold tracking-tight text-muted-foreground uppercase">Mercado</span><span className="block font-display text-sm font-bold text-foreground">− R$ 242,50</span></span></div></div>
      <div className="animate-float-b pointer-events-none absolute hidden sm:block top-[42%] -right-1 z-30 sm:-right-14"><div className="flex min-w-[190px] items-center gap-3 rounded-2xl border border-border bg-card p-3.5 shadow-[var(--shadow-lift)]"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><Plus className="size-5" /></span><span><span className="block text-[10px] font-bold tracking-tight text-muted-foreground uppercase">Salário mensal</span><span className="block font-display text-sm font-bold text-primary">+ R$ 8.500,00</span></span></div></div>
      <div className="animate-float-c pointer-events-none absolute hidden sm:block bottom-[14%] -left-1 z-30 sm:-left-20"><div className="gradient-stage flex items-center gap-3 rounded-2xl p-3.5 shadow-[var(--shadow-lift)]"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-white/15 text-primary-foreground"><Sparkles className="size-4" /></span><p className="text-xs font-medium text-primary-foreground">Fin: “Você economizou 12% este mês”</p></div></div>
      <div className="animate-fin-rise relative z-20 mx-auto h-[520px] w-[252px] rounded-[3rem] border-[6px] border-ink bg-ink p-2.5 shadow-[var(--shadow-stage)] sm:h-[590px] sm:w-[290px]"><div className="relative h-full w-full overflow-hidden rounded-[2.2rem] bg-card text-card-foreground"><div className="p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><span className="grid size-8 place-items-center rounded-full bg-primary/10 text-[11px] font-bold text-primary">G</span><span className="size-2.5 rounded-full bg-primary" /></div><p className="text-[10px] font-semibold tracking-[0.14em] text-muted-foreground uppercase">Saldo disponível</p><p className="mt-1 font-display text-[26px] font-extrabold tracking-tight sm:text-3xl">R$ 4.582,90</p><div className="mt-4 grid grid-cols-2 gap-2.5"><div className="rounded-2xl bg-muted p-3"><div className="flex items-center gap-1 text-[10px] font-semibold text-muted-foreground"><ArrowUpRight className="size-3 text-primary" /> Entrou</div><p className="mt-1 text-sm font-bold text-primary">R$ 6.200</p></div><div className="rounded-2xl bg-muted p-3"><div className="flex items-center gap-1 text-[10px] font-semibold text-muted-foreground"><ArrowDownRight className="size-3 text-danger" /> Saiu</div><p className="mt-1 text-sm font-bold">R$ 1.617</p></div></div><div className="mt-4 space-y-2.5"><MiniRow icon={ShoppingBag} label="Mercado" value="− R$ 242,50" /><MiniRow icon={Car} label="Uber" value="− R$ 32,90" /><MiniRow icon={ArrowUpRight} label="Salário" value="+ R$ 8.500,00" income /></div></div></div></div>
    </div>
  );
}
function MiniRow({ icon: Icon, label, value, income = false }: { icon: typeof ShoppingBag; label: string; value: string; income?: boolean }) {
  return <div className="flex items-center gap-2.5 rounded-xl border border-border p-2.5"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-muted text-muted-foreground"><Icon className="size-3.5" /></span><span className="min-w-0 flex-1 truncate text-xs font-medium">{label}</span><span className={`shrink-0 text-xs font-bold tabular-nums ${income ? "text-primary" : "text-foreground"}`}>{value}</span></div>;
}
