import { useEffect, useMemo, useState } from "react";
import { Mic, MicOff, Send, Sparkles, X } from "lucide-react";
import { useAccounts, useProfile, useTransactions } from "@/hooks/useFinanceData";
import { useAuth } from "@/hooks/useAuth";
import { availableBalance, totalsFor, buildPeriod } from "@/lib/finance";
import { formatBRL, monthRange } from "@/lib/format";
import { saveTransaction } from "@/lib/transactions";
import { cn } from "@/lib/utils";
import { buildFinAnswer } from "@/lib/fin-engine";
import type { PaymentMethod, Recurrence, TransactionType } from "@/types/finance";

type Message = { from: "fin" | "user"; text: string };
type Recognition = { lang: string; continuous: boolean; interimResults: boolean; onresult: ((event: any) => void) | null; onerror: ((event?: any) => void) | null; onend: (() => void) | null; start: () => void; stop: () => void };
declare global { interface Window { SpeechRecognition?: new () => Recognition; webkitSpeechRecognition?: new () => Recognition } }

function money(text: string) { const m = text.toLowerCase().match(/(?:r\$\s*)?(\d{1,3}(?:\.\d{3})*(?:,\d{1,2})?|\d+(?:,\d{1,2})?|\d+(?:\.\d{1,2})?)/); if (!m) return null; const n = m[1].includes(",") ? Number(m[1].replace(/\./g, "").replace(",", ".")) : Number(m[1]); return Number.isFinite(n) && n > 0 ? n : null; }
function parseTransaction(text: string): { type: TransactionType; amount: number; description: string } | null { const amount = money(text); if (!amount) return null; const q = text.toLowerCase(); const income = /\b(recebi|ganhei|sal[aá]rio|renda|dep[oó]sito|vendi|pagaram|entrou)\b/i.test(q); const expense = /\b(gastei|paguei|comprei|compra|despesa|sa[ií]da|gasto)\b/i.test(q); if (!income && !expense) return null; const description = q.replace(/(?:r\$\s*)?(\d{1,3}(?:\.\d{3})*(?:,\d{1,2})?|\d+(?:,\d{1,2})?|\d+(?:\.\d{1,2})?)/, "").replace(/\b(reais?|real)\b/g, "").replace(/^(eu\s+)?(recebi|ganhei|sal[aá]rio|renda|dep[oó]sito|vendi|pagaram|entrou|gastei|paguei|comprei|compra|despesa|sa[ií]da|gasto)\s*/i, "").trim(); return { type: income && !expense ? "income" : "expense", amount, description: description || "Lançamento registrado pelo Fin" }; }

export function FinancialAssistant({ className }: { className?: string }) {
  const { user } = useAuth(); const { data: profile } = useProfile(); const { data: transactions = [] } = useTransactions(); const { data: accounts = [] } = useAccounts();
  const [open, setOpen] = useState(false); const [input, setInput] = useState(""); const [listening, setListening] = useState(false); const [saving, setSaving] = useState(false); const [messages, setMessages] = useState<Message[]>([]);
  const period = useMemo(() => buildPeriod("current", monthRange()), []); const totals = useMemo(() => totalsFor(transactions, period), [transactions, period]); const balance = availableBalance(accounts, transactions); const income = totals.income || Number(profile?.monthly_income ?? 0);
  const context = useMemo(() => ({ transactions: transactions as any, balance, monthlyIncome: Number(profile?.monthly_income ?? 0) }), [transactions, balance, profile?.monthly_income]);

  function listen() { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) { setInput("Seu navegador não oferece voz. Use Chrome ou Edge e permita o microfone."); return; } const r = new Recognition(); r.lang = "pt-BR"; r.continuous = true; r.interimResults = true; r.onresult = (e: any) => { let text = ""; for (let i = e.resultIndex ?? 0; i < e.results.length; i++) text += e.results[i]?.[0]?.transcript || ""; if (text.trim()) setInput(text.trim()); }; r.onerror = (e: any) => { setListening(false); if (e?.error === "not-allowed" || e?.error === "service-not-allowed") setInput("Permita o microfone nas configurações do navegador para falar com o Fin."); }; r.onend = () => setListening(false); setListening(true); try { r.start(); } catch { setListening(false); } }
  useEffect(() => { const fn = (event: Event) => { const detail = (event as CustomEvent<{ listen?: boolean }>).detail; setOpen(true); if (detail?.listen) window.setTimeout(listen, 150); }; window.addEventListener("finanzzi:open-assistant", fn); return () => window.removeEventListener("finanzzi:open-assistant", fn); }, []);
  useEffect(() => { if (open && messages.length === 0) setMessages([{ from: "fin", text: `Olá${profile?.name ? `, ${profile.name.split(" ")[0]}` : ""}! Eu sou o Fin. Posso conversar sobre seu dinheiro, analisar decisões e registrar entradas ou saídas. O que você quer resolver?` }]); }, [open, messages.length, profile?.name]);

  async function send() { const text = input.trim(); if (!text || saving) return; setMessages(m => [...m, { from: "user", text }]); setInput(""); const tx = parseTransaction(text); if (tx && user) { setSaving(true); try { await saveTransaction({ userId: user.id, description: tx.description, amount: tx.amount, type: tx.type, categoryId: null, accountId: accounts[0]?.id ?? null, cardId: null, date: new Date().toISOString().slice(0,10), method: "cash" as PaymentMethod, cardId: null, notes: "Registrado pelo Fin", recurrence: "none" as Recurrence }); const label = tx.type === "income" ? "entrada" : "saída"; setMessages(m => [...m, { from: "fin", text: `Pronto. Registrei uma ${label} de ${formatBRL(tx.amount)}${tx.description ? ` em ${tx.description}` : ""}. Já está salva no FINANZZI.` }]); } catch { setMessages(m => [...m, { from: "fin", text: "Eu entendi o lançamento, mas não consegui salvá-lo agora. Tente novamente em alguns segundos." }]); } finally { setSaving(false); } return; } setMessages(m => [...m, { from: "fin", text: buildFinAnswer(text, context) }]); }

  if (!open) return <button type="button" onClick={() => setOpen(true)} aria-label="Abrir Fin" className={cn("fixed bottom-24 right-4 z-40 grid size-14 place-items-center overflow-hidden rounded-full border-2 border-primary/20 bg-[#062117] shadow-2xl transition-transform hover:scale-105 active:scale-95", className)}><img src="/fin-assistente.png" alt="Fin" className="h-full w-full object-cover" /><span className="absolute bottom-0 right-0 size-3 rounded-full border-2 border-[#062117] bg-emerald-400" /></button>;
  return <div className={cn("fixed bottom-24 right-3 z-50 w-[calc(100vw-1.5rem)] max-w-[400px] overflow-hidden rounded-3xl border border-primary/20 bg-[#071a12] text-white shadow-2xl", className)}><div className="flex items-center justify-between border-b border-white/10 bg-primary/10 p-4"><div className="flex items-center gap-3"><div className="size-10 overflow-hidden rounded-xl"><img src="/fin-assistente.png" alt="Fin" className="h-full w-full object-cover" /></div><div><div className="flex items-center gap-1 text-sm font-bold"><Sparkles className="size-3.5 text-emerald-300" /> Fin</div><p className="text-xs text-white/50">Assistente financeiro</p></div></div><button type="button" onClick={() => setOpen(false)} className="rounded-full p-2 text-white/50 hover:bg-white/10" aria-label="Fechar"><X className="size-4" /></button></div><div className="max-h-[55vh] space-y-3 overflow-y-auto p-4">{messages.map((m,i)=><div key={`${m.from}-${i}`} className={cn("max-w-[90%] rounded-2xl px-3 py-2 text-sm leading-5",m.from === "user" ? "ml-auto bg-emerald-400 font-medium text-[#032013]" : "bg-white/[0.07] text-white/85")}>{m.text}</div>)}</div><div className="border-t border-white/10 p-3"><div className="flex gap-2 rounded-2xl border border-white/10 bg-white/[0.04] p-1"><button type="button" onClick={listening ? undefined : listen} className={cn("grid size-10 shrink-0 place-items-center rounded-xl",listening?"bg-red-400":"bg-emerald-400 text-[#032013]")} aria-label="Microfone">{listening?<MicOff className="size-4 text-white"/>:<Mic className="size-4"/>}</button><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void send()}} disabled={saving} placeholder={listening?"Estou ouvindo...":saving?"Salvando...":"Converse com o Fin..."} className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none placeholder:text-white/30"/><button type="button" onClick={()=>void send()} disabled={saving} className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-400 text-[#032013] disabled:opacity-50" aria-label="Enviar"><Send className="size-4"/></button></div><p className="mt-2 px-1 text-[10px] text-white/35">O Fin usa seus dados do FINANZZI para responder com contexto.</p></div></div>;
}
