import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { GlassCard } from '@/components/GlassCard';
import { formatBRL } from '@/lib/finance';
import type { Bill, Profile } from '@/lib/types';
import { Ionicons } from '@expo/vector-icons';

const C={bg:'#0A0A0C',text:'#F5F5F7',muted:'#8E8E96',orange:'#D95F18',green:'#63C98F',red:'#FF6F72',line:'rgba(255,255,255,0.09)'};
export function SpendCapacitySheet({visible,profile,bills,onClose}:{visible:boolean;profile:Profile|null;bills:Bill[];onClose:()=>void}){
  const commitments=bills.reduce((sum,bill)=>sum+Number(bill.amount),0); const balance=Number(profile?.current_balance??0); const monthlyIncome=Number(profile?.monthly_income??0); const committed=Math.max(0,balance-commitments); const day=new Date(); const end=new Date(day.getFullYear(),day.getMonth()+1,0).getDate(); const remainingDays=Math.max(1,end-day.getDate()+1); const daily=Math.max(0,committed/remainingDays); const monthlyMargin=Math.max(0,monthlyIncome-commitments);
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><View style={styles.screen}><View style={styles.top}><Text style={styles.title}>Posso gastar hoje?</Text><Pressable onPress={onClose}><Text style={styles.close}>Fechar</Text></Pressable></View><View style={styles.content}><Text style={styles.kicker}>DECISÃO FINANCEIRA</Text><Text style={styles.hero}>{formatBRL(daily)}</Text><Text style={styles.heroLabel}>margem diária estimada</Text><GlassCard style={styles.card} tintColor="rgba(217,95,24,0.08)"><Row icon="wallet-outline" label="Saldo atual" value={formatBRL(balance)}/><Row icon="calendar-outline" label="Compromissos próximos" value={formatBRL(commitments)} danger={commitments>0}/><Row icon="shield-checkmark-outline" label="Depois dos compromissos" value={formatBRL(committed)} good/></GlassCard><Text style={styles.explanation}>{committed>0?`Com ${remainingDays} dias restantes, esse valor mantém seus compromissos atuais cobertos.`:'Seu saldo não cobre todos os compromissos cadastrados. Evite novos gastos até revisar as próximas contas.'}</Text><GlassCard style={styles.margin}><Text style={styles.marginLabel}>Margem do mês</Text><Text style={styles.marginValue}>{formatBRL(monthlyMargin)}</Text><Text style={styles.marginText}>Renda mensal menos compromissos pendentes.</Text></GlassCard></View></View></Modal>;
}
function Row({icon,label,value,danger,good}:{icon:any;label:string;value:string;danger?:boolean;good?:boolean}){return <View style={styles.row}><Ionicons name={icon} size={19} color={danger?C.red:good?C.green:C.orange}/><Text style={styles.rowLabel}>{label}</Text><Text style={[styles.rowValue,danger&&{color:C.red},good&&{color:C.green}]}>{value}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},top:{height:60,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:C.text,fontSize:17,fontWeight:'700'},close:{color:C.orange,fontSize:16,fontWeight:'600'},content:{padding:24},kicker:{color:C.orange,fontSize:11,fontWeight:'800',letterSpacing:1.5},hero:{color:C.text,fontSize:48,fontWeight:'800',letterSpacing:-2,marginTop:10},heroLabel:{color:C.muted,fontSize:14,marginTop:-3,marginBottom:24},card:{borderRadius:24,paddingHorizontal:16},row:{minHeight:58,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:C.line},rowLabel:{color:C.muted,fontSize:13,flex:1},rowValue:{color:C.text,fontSize:14,fontWeight:'700'},explanation:{color:C.muted,fontSize:14,lineHeight:21,marginTop:18},margin:{borderRadius:22,padding:18,marginTop:22},marginLabel:{color:C.muted,fontSize:12,fontWeight:'700'},marginValue:{color:C.text,fontSize:25,fontWeight:'800',marginTop:5},marginText:{color:C.muted,fontSize:12,marginTop:4}});
